"use client"
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import { store } from "../redux/store";
import { usePathname } from "next/navigation";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "E-com",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();

  const hidelayout = ["/login","/register"].includes(pathname);


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Provider store={store}>
          {!hidelayout && <Header/>}
          {!hidelayout && <Navbar/>}
          {/* <Header />
          <Navbar /> */}
          {children}
         {!hidelayout && <Footer />}
        </Provider>
      </body>
    </html>
  );
}
